spring:
  datasource:
    url: jdbc:h2:~/fiapcartoes;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    password: fiap

  h2:
    console:
      enabled:
        true
      path:
        /h2

file:
  input: classpath:cliente.txt