spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:mydb
    username: fiap
    password: fiap

server:
  port: 8090

  h2:
    console:
      enabled:
        true
      path:
        /h2

file:
  input: classpath:lista_alunos.txt